version: '3.5'


services:
  newsletter-subscription-app:
    image: newsletter-subscription
    ports:
      - "127.0.0.1:8083:8083"
    volumes:
      - newsletter_subscription_app_files:/workspace/files
    networks:
      - newsletter_network
      - gateway_network

  newsletter-subscription_db:
    image: postgres:12.7
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=newsletter_subscription
    networks:
      - newsletter_network


volumes:
  pgdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/newsletter-subscription/postgres/pgdata
  newsletter_subscription_app_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: $HOME/artifacts/newsletter-subscription/app_files


networks:
  newsletter_network:
    name: "newsletter_network"
    driver: bridge
  gateway_network:
    external: true